export type UserRole = "staff" | "admin" | "superuser";

export type Permission =
  // Plans
  | "subscriptions.plans.add"
  | "subscriptions.plans.read"
  | "subscriptions.plans.read_own"
  | "subscriptions.plans.change"
  | "subscriptions.plans.change_own"
  | "subscriptions.plans.delete"
  | "subscriptions.plans.manage"
  | "subscriptions.plans.manage_own"
  | "subscriptions.plans.refund"
  // Billing
  | "subscriptions.billing.add"
  | "subscriptions.billing.read"
  | "subscriptions.billing.read_own"
  | "subscriptions.billing.change"
  | "subscriptions.billing.change_own"
  | "subscriptions.billing.delete"
  | "subscriptions.billing.manage"
  | "subscriptions.billing.manage_own"
  | "subscriptions.billing.refund"
  // Usage
  | "subscriptions.usage.add"
  | "subscriptions.usage.read"
  | "subscriptions.usage.read_own"
  | "subscriptions.usage.change"
  | "subscriptions.usage.change_own"
  | "subscriptions.usage.delete"
  | "subscriptions.usage.manage"
  | "subscriptions.usage.manage_own"
  | "subscriptions.usage.refund"
  // Upgrades
  | "subscriptions.upgrades.add"
  | "subscriptions.upgrades.read"
  | "subscriptions.upgrades.read_own"
  | "subscriptions.upgrades.change"
  | "subscriptions.upgrades.change_own"
  | "subscriptions.upgrades.delete"
  | "subscriptions.upgrades.manage"
  | "subscriptions.upgrades.manage_own"
  | "subscriptions.upgrades.refund"
  // Settings
  | "subscriptions.settings.add"
  | "subscriptions.settings.read"
  | "subscriptions.settings.read_own"
  | "subscriptions.settings.change"
  | "subscriptions.settings.change_own"
  | "subscriptions.settings.delete"
  | "subscriptions.settings.manage"
  | "subscriptions.settings.manage_own"
  | "subscriptions.settings.refund"
  // Platform
  | "subscriptions.platform.add"
  | "subscriptions.platform.read"
  | "subscriptions.platform.read_own"
  | "subscriptions.platform.change"
  | "subscriptions.platform.change_own"
  | "subscriptions.platform.delete"
  | "subscriptions.platform.manage"
  | "subscriptions.platform.manage_own"
  | "subscriptions.platform.refund"
  // Tenants
  | "subscriptions.tenants.add"
  | "subscriptions.tenants.read"
  | "subscriptions.tenants.read_own"
  | "subscriptions.tenants.change"
  | "subscriptions.tenants.change_own"
  | "subscriptions.tenants.delete"
  | "subscriptions.tenants.manage"
  | "subscriptions.tenants.manage_own"
  | "subscriptions.tenants.refund"
  // Invoices
  | "subscriptions.invoices.add"
  | "subscriptions.invoices.read"
  | "subscriptions.invoices.read_own"
  | "subscriptions.invoices.change"
  | "subscriptions.invoices.change_own"
  | "subscriptions.invoices.delete"
  | "subscriptions.invoices.manage"
  | "subscriptions.invoices.manage_own"
  | "subscriptions.invoices.refund"
  // Notifications
  | "subscriptions.notifications.add"
  | "subscriptions.notifications.read"
  | "subscriptions.notifications.read_own"
  | "subscriptions.notifications.change"
  | "subscriptions.notifications.change_own"
  | "subscriptions.notifications.delete"
  | "subscriptions.notifications.manage"
  | "subscriptions.notifications.manage_own"
  | "subscriptions.notifications.refund"
  // Config
  | "subscriptions.config.view"
  | "subscriptions.config.manage"
  // Users
  | "subscriptions.users.manage";

export interface UserProfile {
  id: string;
  email: string;
  fullName: string;
  roles: UserRole[];
  permissions: Permission[];
  organizationId: string;
  tenantId: string;
  tenantSlug: string;
  isPlatformOwner?: boolean;
  isSuperUser?: boolean;
}
